import { expect, test } from "./dashboard.fixture.mjs"

test("copies a rule without global targets and verifies guarded undo", async ({ dashboard }) => {
  const { page, requests, zoneNames } = dashboard
  await page.getByPlaceholder("Search facets, values, or zones").fill("Protect service")
  const copy = page.getByRole("button", { name: "Copy Protect service between zones" })
  await expect(copy).toBeEnabled()
  await copy.click()
  const dialog = page.getByRole("dialog", { name: "Copy Protect service", exact: true })
  await expect(dialog.getByRole("button", { name: "Review copy" })).toBeDisabled()
  await expect(dialog.getByRole("checkbox", { name: zoneNames[0], exact: true })).toHaveCount(0)
  await dialog.getByRole("checkbox", { name: zoneNames[1], exact: true }).check()
  await dialog.getByRole("button", { name: "Review copy" }).click()
  const confirmation = page.locator("#confirm-dialog")
  await expect(confirmation).toBeVisible()
  await expect(confirmation).toContainText(zoneNames[1])
  await expect(confirmation.locator(".operation-change")).toContainText("EnabledYes")
  expect(requests.filter((request) => request.method !== "GET")).toHaveLength(0)
  await confirmation.getByRole("checkbox").check()
  await confirmation.getByRole("button", { name: "Apply and verify" }).click()
  await expect(page.locator("#toast-message")).toContainText("live verification passed")
  const writes = requests.filter((request) => request.method === "PATCH")
  expect(writes).toHaveLength(1)
  expect(writes[0].path).toContain(`zone-${zoneNames[1]}/rulesets/`)
  expect(writes[0].body.enabled).toBe(true)
  await page.getByRole("button", { name: /Activity 1:/ }).click()
  await page.getByRole("button", { name: "Review guarded undo" }).click()
  await expect(confirmation).toBeVisible()
  await confirmation.getByRole("checkbox").check()
  await confirmation.getByRole("button", { name: "Apply and verify" }).click()
  await expect(page.locator("#toast-message")).toHaveText("Undo succeeded and live verification passed")
  expect(requests.filter((request) => request.method === "PATCH").at(-1).body.enabled).toBe(false)
})

test("offers cross-zone copying directly inside the ruleset workspace", async ({ dashboard }) => {
  const { page, zoneNames } = dashboard
  await page.getByPlaceholder("Search facets, values, or zones").fill("Protect service")
  await page.getByRole("button", { name: `Open the parent ruleset for Protect service on ${zoneNames[0]}` }).click()
  const workspace = page.locator("#ruleset-dialog")
  await workspace.getByRole("button", { name: "Copy Protect service to other zones" }).click()
  const dialog = page.locator("#rule-copy-dialog")
  await expect(dialog).toBeVisible()
  await dialog.getByRole("checkbox", { name: zoneNames[1], exact: true }).check()
  await dialog.getByRole("button", { name: "Cancel" }).click()
  await expect(workspace).toBeVisible()
  expect(dashboard.requests.filter((request) => request.method !== "GET")).toHaveLength(0)
})
