import { test, expect } from "./dashboard.fixture.mjs"

test("Worker incident journey reviews a schedule-only remedy and keeps recoverable history", async ({ dashboard }) => {
  const { page } = dashboard
  await page.getByRole("button", { name: "Workers", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Worker diagnostics", exact: true })
  await dialog.getByLabel("Worker name or finding ID").fill("example-worker")
  await dialog.getByRole("button", { name: "Inspect Worker", exact: true }).click()
  await expect(dialog.getByRole("status")).toHaveText("Trigger compatibility: mismatch")
  await expect(dialog.getByRole("heading", { name: "HTTP responses on this page" })).toBeVisible()
  await expect(dialog).not.toContainText("PRIVATE-PAYLOAD-MUST-NOT-ESCAPE")
  await dialog.getByRole("button", { name: "Record incident", exact: true }).click()
  await expect(dialog.getByRole("status")).toContainText("Saved incident-")
  await dialog.getByText("Schedule intent, reviewed changes and recovery", { exact: true }).click()
  await dialog.getByRole("combobox", { name: "Schedule intent", exact: true }).selectOption("disabled")
  await dialog.getByLabel("Owning deployment configuration").fill("example-project:wrangler.jsonc")
  await dialog.getByLabel("Reviewed configuration reconciliation step").fill("Set triggers.crons to [] before deployment")
  await dialog.getByRole("button", { name: "Review intent save", exact: true }).click()
  await expect(dialog.getByRole("button", { name: "Apply reviewed change" })).toBeDisabled()
  await dialog.getByRole("checkbox").check()
  await dialog.getByRole("button", { name: "Apply reviewed change" }).click()
  await expect(dialog.getByRole("status")).toHaveText("saved")
  await dialog.getByRole("button", { name: "Review schedule change", exact: true }).click()
  await expect(dialog.getByRole("button", { name: "Apply reviewed change" })).toBeDisabled()
  expect(dashboard.requests.filter((request) => request.method === "PUT" && request.path.endsWith("/schedules"))).toHaveLength(0)
  await dialog.getByRole("checkbox").check()
  await dialog.getByRole("button", { name: "Apply reviewed change" }).click()
  await expect(dialog.getByRole("status")).toHaveText("propagation-pending")
  expect(dashboard.requests.filter((request) => request.method === "PUT" && request.path.endsWith("/schedules"))).toHaveLength(1)
  await dialog.getByRole("button", { name: "Verify after change" }).click()
  await expect(dialog.getByRole("status")).toHaveText("propagation-pending")
  await dialog.getByRole("button", { name: "Load history and intent" }).click()
  await expect(dialog.getByText(/supersedes incident-/)).toBeVisible()
  await dialog.getByRole("button", { name: "Review guarded undo" }).click()
  await dialog.getByRole("checkbox").check()
  await dialog.getByRole("button", { name: "Apply reviewed change" }).click()
  await expect(dialog.getByRole("status")).toHaveText("propagation-pending")
})

test("read-only dashboard exposes Worker inspection without mutation controls", async ({ readOnlyDashboard }) => {
  const { page } = readOnlyDashboard
  await page.getByRole("button", { name: "Workers", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Worker diagnostics", exact: true })
  await dialog.getByLabel("Worker name or finding ID").fill("example-worker")
  await dialog.getByRole("button", { name: "Inspect Worker", exact: true }).click()
  await expect(dialog.getByRole("status")).toHaveText("Trigger compatibility: mismatch")
  await expect(dialog.getByRole("button", { name: "Record incident" })).toBeDisabled()
  await dialog.getByText("Schedule intent, reviewed changes and recovery", { exact: true }).click()
  await dialog.getByRole("combobox", { name: "Schedule intent", exact: true }).selectOption("disabled")
  await dialog.getByLabel("Owning deployment configuration").fill("example-project:wrangler.jsonc")
  await dialog.getByLabel("Reviewed configuration reconciliation step").fill("Set triggers.crons to [] before deployment")
  await dialog.getByRole("button", { name: "Review schedule change", exact: true }).click()
  await dialog.getByRole("checkbox").check()
  await expect(dialog.getByRole("button", { name: "Apply reviewed change" })).toBeDisabled()
})
